name: Facebook Group Comment Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 3. Install Dependencies
        run: npm install

      - name: 4. Compile group.js with Bytenode
        run: npx bytenode --compile group.js

      - name: 5. Run the Group Bot
        run: node -r bytenode group.jsc
        env:
          FACEBOOK_COOKIES: ${{ secrets.FACEBOOK_COOKIES }}
          BOT_LICENSE_EMAIL: ${{ secrets.BOT_LICENSE_EMAIL }}

      - name: 6. Commit and Push Group Log File
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          LOG_FILE="ceklink_group.txt"

          if [ -s $LOG_FILE ]; then
            git add $LOG_FILE
            if ! git diff --staged --quiet; then
              git commit -m "Update group comment log ($LOG_FILE)"
              git push
            else
              echo "Tidak ada perubahan pada $LOG_FILE untuk di-commit."
            fi
          else
            echo "$LOG_FILE kosong atau tidak ada, tidak di-commit."
          fi
      
      - name: 7. Upload Debug Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots-group
          path: artifacts/
